#define APP_NAME container_example
#define STR(s) #s
#define APP_REPO_COMMAND(APP_REPO) STR(git clone APP_REPO)
#define ROOT_PASSWORD_STRING(ROOT_PASSWORD) STR(root:ROOT_PASSWORD)
FROM ubuntu:14.04
MAINTAINER RailsMasters

RUN apt-get update
RUN apt-get -y install git gcc autoconf bison build-essential libssl-dev libyaml-dev libreadline6 libreadline6-dev zlib1g zlib1g-dev libsqlite3-dev vim screen curl wget nodejs openssh-server

RUN git clone https://github.com/sstephenson/rbenv.git /usr/local/rbenv
RUN echo '# rbenv setup' > /etc/profile.d/rbenv.sh
RUN echo 'export RBENV_ROOT=/usr/local/rbenv' >> /etc/profile.d/rbenv.sh
RUN echo 'export PATH="$RBENV_ROOT/bin:$PATH"' >> /etc/profile.d/rbenv.sh
RUN echo 'eval "$(rbenv init -)"' >> /etc/profile.d/rbenv.sh
RUN chmod +x /etc/profile.d/rbenv.sh
 
RUN mkdir /usr/local/rbenv/plugins
RUN git clone https://github.com/sstephenson/ruby-build.git /usr/local/rbenv/plugins/ruby-build
 
ENV RBENV_ROOT /usr/local/rbenv
 
ENV PATH "$PATH:$RBENV_ROOT/bin:$RBENV_ROOT/shims"
RUN rbenv install 2.0.0-p576
RUN rbenv global 2.0.0-p576
RUN bash -l -c "gem install bundler foreman"
RUN rbenv rehash
RUN adduser --disabled-password --gecos "" app
WORKDIR /home/app
RUN su app -c APP_REPO_COMMAND(APP_REPO)
RUN ln -s /home/app/APP_NAME /app
USER app
WORKDIR /app
RUN bash -l -c "bundle install --deployment"

USER root
RUN mkdir /var/run/sshd
EXPOSE 22
EXPOSE 3000
RUN echo ROOT_PASSWORD_STRING(ROOT_PASSWORD) | chpasswd
RUN sed -i 's/PermitRootLogin without-password/PermitRootLogin yes/' /etc/ssh/sshd_config
CMD /usr/sbin/sshd && su app -c 'bash -l -c "foreman start"'
